/* KHAMRAH PAGE JS */
const khamrahProduct={id:999,name:'Khamrah Body Mist',price:145000,image:'assets/khamrah-campaign.jpg',category:'masculino',description:'Olor a Poder. Firma de Respeto.',featured:true,rating:5};
document.addEventListener('DOMContentLoaded',()=>{initKhamrahPage();updateCartUI()});
function initKhamrahPage(){initQuantity();initAddToCart();initScrollButton()}
function initQuantity(){const dec=document.getElementById('decreaseQty'),inc=document.getElementById('increaseQty'),input=document.getElementById('productQuantity');dec?.addEventListener('click',()=>{let v=parseInt(input.value);if(v>1)input.value=v-1});inc?.addEventListener('click',()=>{let v=parseInt(input.value);if(v<10)input.value=v+1})}
function initAddToCart(){const btn=document.getElementById('addToCartBtn'),input=document.getElementById('productQuantity');btn?.addEventListener('click',()=>{const qty=parseInt(input.value)||1;let cart=JSON.parse(localStorage.getItem('cart'))||[];const exists=cart.find(i=>i.id===khamrahProduct.id);if(exists){exists.quantity+=qty}else{cart.push({...khamrahProduct,quantity:qty})}
localStorage.setItem('cart',JSON.stringify(cart));updateCartUI();btn.innerHTML='<i class="fas fa-check"></i> ¡AGREGADO!';btn.style.background='#27ae60';setTimeout(()=>{btn.innerHTML='<i class="fas fa-shopping-cart"></i> AGREGAR AL CARRITO';btn.style.background='';input.value=1},2000);showKhamrahNotification(`${qty}x ${khamrahProduct.name} agregado al carrito!`)})}
function initScrollButton(){const btn=document.getElementById('scrollToProduct');btn?.addEventListener('click',()=>{document.getElementById('productSection')?.scrollIntoView({behavior:'smooth'})})}
function showKhamrahNotification(msg){const n=document.createElement('div');n.style.cssText='position:fixed;top:100px;right:20px;background:linear-gradient(135deg,#c4a76b,#f6d365);color:#000;padding:1.5rem 2.5rem;border-radius:20px;box-shadow:0 10px 40px rgba(196,167,107,0.5);z-index:99999;font-weight:700;animation:slideIn 0.4s ease';n.innerHTML=`<i class="fas fa-check-circle" style="font-size:1.5rem;margin-right:1rem"></i><span>${msg}</span>`;document.body.appendChild(n);setTimeout(()=>{n.style.animation='slideOut 0.3s ease';setTimeout(()=>n.remove(),300)},3000)}
const style=document.createElement('style');style.textContent='@keyframes slideIn{from{transform:translateX(100%);opacity:0}to{transform:translateX(0);opacity:1}}@keyframes slideOut{from{transform:translateX(0);opacity:1}to{transform:translateX(100%);opacity:0}}';document.head.appendChild(style);
console.log('✅ Khamrah page loaded');
